# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_current',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_send',
        ),
        migrations.AddField(
            model_name='post',
            name='new',
            field=models.CharField(default='', max_length=5),
        ),
    ]
