# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180322_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new',
        ),
        migrations.AddField(
            model_name='post',
            name='user_pk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='user_send',
            field=models.IntegerField(default=0),
        ),
    ]
