# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newmusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files_sv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filessv', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to='newmusic.Files')),
            ],
        ),
    ]
