# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmusic', '0005_auto_20180330_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files_sv',
            name='users',
        ),
        migrations.AddField(
            model_name='files_sv',
            name='users',
            field=models.ManyToManyField(to='newmusic.Files'),
        ),
    ]
